version: '3.8'

services:

 db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: friend-management
      POSTGRES_PASSWORD: "1234" 
      POSTGRES_DB: friend-management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=db
    depends_on:
      - db

volumes:
  postgres_data: