// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Blocks            string
	FriendConnections string
	Subscriptions     string
	Users             string
}{
	Blocks:            "blocks",
	FriendConnections: "friend_connections",
	Subscriptions:     "subscriptions",
	Users:             "users",
}
